export const PLC_CONFIG = {
  variables: {
    fechaHora: {
      name: 'Fecha y Hora',
      address: 'P#DB51.DBX164.0',
      db: 51,
      start: 164,
      size: 8,
      type: 'string',
      comment: 'Fecha y hora del sistema',
    },
    vb: {
      name: 'VB',
      address: '%DB1.DBD24',
      db: 1,
      start: 24,
      size: 4,
      type: 'real',
      comment: 'Variable VB',
    },
    cb: {
      name: 'CB',
      address: '%DB1.DBW28',
      db: 1,
      start: 28,
      size: 2,
      type: 'int',
      comment: 'Variable CB',
    },
    sw: {
      name: 'SW',
      address: '%DB1.DBW50',
      db: 1,
      start: 50,
      size: 2,
      type: 'int',
      comment: 'Variable SW',
    },
    et: {
      name: 'ET',
      address: '%DB1.DBW16',
      db: 1,
      start: 16,
      size: 2,
      type: 'int',
      comment: 'Variable ET',
    },
    pt: {
      name: 'PT',
      address: '%DB1.DBW18',
      db: 1,
      start: 18,
      size: 2,
      type: 'int',
      comment: 'Variable PT',
    },
    vs: {
      name: 'VS',
      address: '%DB1.DBD36',
      db: 1,
      start: 36,
      size: 4,
      type: 'real',
      comment: 'Variable VS',
    },
    cs: {
      name: 'CS',
      address: '%DB1.DBW34',
      db: 1,
      start: 34,
      size: 2,
      type: 'int',
      comment: 'Variable CS',
    },
  },
  connection: {
    defaultRack: 0,
    defaultSlot: 1,
    timeout: 5000,
    retryAttempts: 3,
  },
};
